/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Vending_Machine;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        VendingMachine vendingMachine = new VendingMachine();
        // User Login Interface
        vendingMachine.userLogIn();
        // Main Menu
        vendingMachine.showMenu();
        while(true){
            Scanner sc = new Scanner(System.in);

            System.out.print("Input your command: ");
            String command = sc.nextLine();
            String [] parameter = command.split(" ");
            String firstCommand = parameter[0];
            if (firstCommand.equalsIgnoreCase("HELP")) {
                System.out.println();
                System.out.println("BUY: buy some items");
                System.out.println("EXIT: exit vending machine");
                System.out.println("HELP: print this manual");
                System.out.println();
            } else if (firstCommand.equalsIgnoreCase("BUY")) {
                vendingMachine.transaction();
            } else if (firstCommand.equalsIgnoreCase("EXIT")) {
                System.exit(0);
            } else {
                System.out.println("Invalid command, please enter again.");
            }
        }
    }
}
